"""Stage 4 metadata schema and deterministic connector registry seeds."""

from __future__ import annotations

import json
import sqlite3


CONNECTOR_TYPES = {
    "REST_API": {
        "category": "REST_API", "version": "1.0.0",
        "capabilities": ["READ", "WRITE", "DISCOVER_SCHEMA", "INCREMENTAL_READ"],
        "configuration": {"base_url": "url", "path": "string", "method": "GET", "pagination": "NONE"},
        "credentials": {"token": "secret", "api_key": "secret", "username": "string", "password": "secret"},
    },
    "RELATIONAL_DB": {
        "category": "DATABASE", "version": "1.0.0",
        "capabilities": ["READ", "WRITE", "DISCOVER_SCHEMA", "INCREMENTAL_READ", "TRANSACTIONAL_WRITE", "BULK_WRITE"],
        "configuration": {"table": "string", "query": "string", "checkpoint_column": "string", "primary_key": "string"},
        "credentials": {"database_url": "secret"},
    },
    "FILE": {
        "category": "FILE", "version": "1.0.0",
        "capabilities": ["READ", "WRITE", "DISCOVER_SCHEMA", "BULK_WRITE"],
        "configuration": {"format": "CSV|JSON|XML|EXCEL", "encoding": "utf-8", "delimiter": ",", "header_row": 1},
        "credentials": {},
    },
    "SFTP": {
        "category": "SFTP", "version": "1.0.0",
        "capabilities": ["READ", "WRITE", "DISCOVER_SCHEMA", "INCREMENTAL_READ"],
        "configuration": {"host": "string", "port": 22, "base_path": "string", "host_key_fingerprint": "required"},
        "credentials": {"username": "string", "password": "secret", "private_key": "secret"},
    },
    "S3": {
        "category": "OBJECT_STORAGE", "version": "1.0.0",
        "capabilities": ["READ", "WRITE", "DISCOVER_SCHEMA", "INCREMENTAL_READ", "BULK_WRITE"],
        "configuration": {"bucket": "string", "prefix": "string", "endpoint_url": "url"},
        "credentials": {"access_key": "secret", "secret_key": "secret", "session_token": "secret"},
    },
}


def initialize_integration_schema(conn: sqlite3.Connection, now: str) -> None:
    conn.executescript(
        """
        CREATE TABLE IF NOT EXISTS CONNECTOR_TYPES (
            CONNECTOR_TYPE TEXT PRIMARY KEY, CATEGORY TEXT NOT NULL, VERSION TEXT NOT NULL,
            CAPABILITIES_JSON TEXT NOT NULL, CONFIGURATION_SCHEMA_JSON TEXT NOT NULL,
            CREDENTIAL_SCHEMA_JSON TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
            CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_SECRETS (
            SECRET_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, PROVIDER TEXT NOT NULL,
            ENCRYPTED_VALUE TEXT NOT NULL, VALUE_FINGERPRINT TEXT NOT NULL, CREATED_BY TEXT NOT NULL,
            CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_CONNECTIONS (
            CONNECTION_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTOR_TYPE TEXT NOT NULL,
            NAME TEXT NOT NULL, ENVIRONMENT TEXT NOT NULL, CONFIGURATION_JSON TEXT NOT NULL,
            CREDENTIAL_REFERENCE TEXT, STATUS TEXT NOT NULL DEFAULT 'ACTIVE', HEALTH_STATUS TEXT NOT NULL DEFAULT 'UNKNOWN',
            LAST_TESTED_AT TEXT, LAST_SUCCESS_AT TEXT, LAST_FAILURE_AT TEXT, CREATED_BY TEXT NOT NULL,
            CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL, UNIQUE(ORGANIZATION_ID,NAME)
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_SOURCE_OBJECTS (
            SOURCE_OBJECT_ID TEXT PRIMARY KEY, CONNECTION_ID TEXT NOT NULL, NAME TEXT NOT NULL,
            OBJECT_TYPE TEXT NOT NULL, EXTERNAL_PATH TEXT, SOURCE_OBJECT_HASH TEXT,
            DISCOVERED_SCHEMA_JSON TEXT, STATUS TEXT NOT NULL DEFAULT 'ACTIVE', CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL,
            UNIQUE(CONNECTION_ID,NAME)
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_RUNS (
            RUN_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            OPERATION TEXT NOT NULL, STATUS TEXT NOT NULL, STARTED_AT TEXT NOT NULL, COMPLETED_AT TEXT,
            RECORDS_READ INTEGER NOT NULL DEFAULT 0, RECORDS_WRITTEN INTEGER NOT NULL DEFAULT 0,
            BYTES_PROCESSED INTEGER NOT NULL DEFAULT 0, CHECKPOINT_JSON TEXT, ERROR_COUNT INTEGER NOT NULL DEFAULT 0,
            ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0, ERROR_CODE TEXT, ERROR_MESSAGE TEXT,
            IDEMPOTENCY_KEY TEXT, CREATED_BY TEXT NOT NULL, UNIQUE(CONNECTION_ID,IDEMPOTENCY_KEY)
        );
        CREATE TABLE IF NOT EXISTS RAW_INGESTION_ENVELOPES (
            ENVELOPE_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, RUN_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            SOURCE_SYSTEM TEXT NOT NULL, EXTERNAL_TYPE TEXT NOT NULL, EXTERNAL_ID TEXT NOT NULL, SOURCE_VERSION TEXT NOT NULL,
            SOURCE_TIMESTAMP TEXT, INGESTED_AT TEXT NOT NULL, PAYLOAD_HASH TEXT NOT NULL, METADATA_JSON TEXT NOT NULL,
            STATUS TEXT NOT NULL DEFAULT 'INGESTED', UNIQUE(CONNECTION_ID,EXTERNAL_TYPE,EXTERNAL_ID,SOURCE_VERSION)
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_CHECKPOINTS (
            CONNECTION_ID TEXT NOT NULL, SOURCE_OBJECT_ID TEXT NOT NULL DEFAULT '', CHECKPOINT_JSON TEXT NOT NULL,
            UPDATED_AT TEXT NOT NULL, PRIMARY KEY(CONNECTION_ID,SOURCE_OBJECT_ID)
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_SCHEDULES (
            SCHEDULE_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            NAME TEXT NOT NULL, MODE TEXT NOT NULL, EXPRESSION TEXT, STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
            NEXT_RUN_AT TEXT, LAST_RUN_AT TEXT, CREATED_BY TEXT NOT NULL, CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_DEAD_LETTERS (
            DEAD_LETTER_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            RUN_ID TEXT, PAYLOAD_HASH TEXT, ERROR_CODE TEXT NOT NULL, ERROR_MESSAGE TEXT NOT NULL,
            ATTEMPT_COUNT INTEGER NOT NULL, STATUS TEXT NOT NULL DEFAULT 'OPEN', CREATED_AT TEXT NOT NULL,
            REPLAYED_AT TEXT, DISCARDED_AT TEXT
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_SCHEMAS (
            SCHEMA_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, NAME TEXT NOT NULL, VERSION INTEGER NOT NULL,
            SCHEMA_JSON TEXT NOT NULL, BUSINESS_KEY_JSON TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
            CREATED_BY TEXT NOT NULL, CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL,
            UNIQUE(ORGANIZATION_ID,NAME,VERSION)
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_MAPPINGS (
            MAPPING_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            SOURCE_OBJECT_TYPE TEXT NOT NULL, SCHEMA_ID TEXT NOT NULL, VERSION INTEGER NOT NULL,
            MAPPING_JSON TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'ACTIVE', CREATED_BY TEXT NOT NULL,
            CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL,
            UNIQUE(CONNECTION_ID,SOURCE_OBJECT_TYPE,SCHEMA_ID,VERSION)
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_OBJECTS (
            CANONICAL_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, SCHEMA_ID TEXT NOT NULL,
            OBJECT_TYPE TEXT NOT NULL, BUSINESS_KEY TEXT NOT NULL, CURRENT_VERSION INTEGER NOT NULL,
            CURRENT_PAYLOAD_HASH TEXT NOT NULL, VALID_FROM TEXT NOT NULL, VALID_TO TEXT,
            STATUS TEXT NOT NULL DEFAULT 'ACTIVE', CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL,
            UNIQUE(ORGANIZATION_ID,SCHEMA_ID,BUSINESS_KEY)
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_OBJECT_VERSIONS (
            CANONICAL_ID TEXT NOT NULL, VERSION INTEGER NOT NULL, PAYLOAD_HASH TEXT NOT NULL,
            SOURCE_ENVELOPE_ID TEXT NOT NULL, VALID_FROM TEXT NOT NULL, VALID_TO TEXT, CHANGE_TYPE TEXT NOT NULL,
            CREATED_AT TEXT NOT NULL, PRIMARY KEY(CANONICAL_ID,VERSION)
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_SOURCE_REFERENCES (
            CONNECTION_ID TEXT NOT NULL, EXTERNAL_TYPE TEXT NOT NULL, EXTERNAL_ID TEXT NOT NULL,
            CANONICAL_ID TEXT NOT NULL, MATCH_CONFIDENCE REAL NOT NULL DEFAULT 1.0, MATCH_METHOD TEXT NOT NULL DEFAULT 'DETERMINISTIC',
            CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL,
            PRIMARY KEY(CONNECTION_ID,EXTERNAL_TYPE,EXTERNAL_ID)
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_RELATIONSHIPS (
            RELATIONSHIP_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, SOURCE_CANONICAL_ID TEXT NOT NULL,
            TARGET_CANONICAL_ID TEXT NOT NULL, RELATIONSHIP_TYPE TEXT NOT NULL, CONFIDENCE REAL NOT NULL DEFAULT 1.0,
            VALID_FROM TEXT NOT NULL, VALID_TO TEXT, EVIDENCE_JSON TEXT NOT NULL, CREATED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS CANONICAL_QUARANTINE (
            QUARANTINE_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, ENVELOPE_ID TEXT NOT NULL,
            SCHEMA_ID TEXT, ERROR_CODE TEXT NOT NULL, ERROR_DETAILS_JSON TEXT NOT NULL,
            STATUS TEXT NOT NULL DEFAULT 'OPEN', CREATED_AT TEXT NOT NULL, RESOLVED_AT TEXT
        );
        CREATE TABLE IF NOT EXISTS SCHEMA_DRIFT_EVENTS (
            DRIFT_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            SOURCE_OBJECT_TYPE TEXT NOT NULL, PREVIOUS_SCHEMA_HASH TEXT, CURRENT_SCHEMA_HASH TEXT NOT NULL,
            CHANGES_JSON TEXT NOT NULL, STATUS TEXT NOT NULL DEFAULT 'OPEN', DETECTED_AT TEXT NOT NULL, RESOLVED_AT TEXT
        );
        CREATE TABLE IF NOT EXISTS DIGITAL_THREAD_NODES (
            NODE_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, NODE_TYPE TEXT NOT NULL,
            EXTERNAL_KEY TEXT NOT NULL, DISPLAY_NAME TEXT NOT NULL, OBJECT_REFERENCE TEXT,
            ATTRIBUTES_JSON TEXT NOT NULL, VALID_FROM TEXT NOT NULL, VALID_TO TEXT, CREATED_AT TEXT NOT NULL,
            UNIQUE(ORGANIZATION_ID,NODE_TYPE,EXTERNAL_KEY)
        );
        CREATE TABLE IF NOT EXISTS DIGITAL_THREAD_EDGES (
            EDGE_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, SOURCE_NODE_ID TEXT NOT NULL,
            TARGET_NODE_ID TEXT NOT NULL, EDGE_TYPE TEXT NOT NULL, CONFIDENCE REAL NOT NULL,
            EVIDENCE_TYPE TEXT NOT NULL, EVIDENCE_REFERENCE TEXT, ATTRIBUTES_JSON TEXT NOT NULL,
            VALID_FROM TEXT NOT NULL, VALID_TO TEXT, CREATED_AT TEXT NOT NULL,
            UNIQUE(ORGANIZATION_ID,SOURCE_NODE_ID,TARGET_NODE_ID,EDGE_TYPE,EVIDENCE_REFERENCE)
        );
        CREATE TABLE IF NOT EXISTS DIGITAL_THREAD_EVENTS (
            THREAD_EVENT_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, NODE_ID TEXT NOT NULL,
            EVENT_TYPE TEXT NOT NULL, EVENT_TIME TEXT NOT NULL, ACTOR_ID TEXT, SOURCE_SYSTEM TEXT,
            EVIDENCE_REFERENCE TEXT, PAYLOAD_JSON TEXT NOT NULL, CREATED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_EVENTS (
            EVENT_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT NOT NULL,
            EVENT_TYPE TEXT NOT NULL, EXTERNAL_ID TEXT NOT NULL, EVENT_VERSION TEXT NOT NULL,
            EVENT_TIME TEXT NOT NULL, RECEIVED_AT TEXT NOT NULL, PAYLOAD_HASH TEXT NOT NULL,
            STATUS TEXT NOT NULL DEFAULT 'RECEIVED', ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0,
            UNIQUE(CONNECTION_ID,EXTERNAL_ID,EVENT_VERSION)
        );
        CREATE TABLE IF NOT EXISTS SYNCHRONIZATION_JOBS (
            SYNC_JOB_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, NAME TEXT NOT NULL,
            SOURCE_CONNECTION_ID TEXT NOT NULL, TARGET_CONNECTION_ID TEXT, MAPPING_ID TEXT,
            DIRECTION TEXT NOT NULL, MODE TEXT NOT NULL, DELETION_POLICY TEXT NOT NULL DEFAULT 'IGNORE',
            CONFLICT_STRATEGY TEXT NOT NULL DEFAULT 'MANUAL', STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
            CREATED_BY TEXT NOT NULL, CREATED_AT TEXT NOT NULL, UPDATED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS RECONCILIATION_RUNS (
            RECONCILIATION_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, SYNC_JOB_ID TEXT,
            INTEGRATION_RUN_ID TEXT, STATUS TEXT NOT NULL, SOURCE_COUNT INTEGER NOT NULL,
            TARGET_COUNT INTEGER NOT NULL, MATCHED_COUNT INTEGER NOT NULL, MISMATCH_COUNT INTEGER NOT NULL,
            SOURCE_HASH TEXT, TARGET_HASH TEXT, RULES_JSON TEXT NOT NULL, RESULT_JSON TEXT NOT NULL,
            STARTED_AT TEXT NOT NULL, COMPLETED_AT TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_CONFLICTS (
            CONFLICT_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, SYNC_JOB_ID TEXT,
            CANONICAL_ID TEXT, CONFLICT_TYPE TEXT NOT NULL, BASE_HASH TEXT, SOURCE_HASH TEXT, TARGET_HASH TEXT,
            RESOLUTION_STRATEGY TEXT, RESOLVED_HASH TEXT, STATUS TEXT NOT NULL DEFAULT 'OPEN',
            CREATED_AT TEXT NOT NULL, RESOLVED_AT TEXT, RESOLVED_BY TEXT
        );
        CREATE TABLE IF NOT EXISTS INFORMATION_CATALOGUE (
            CATALOGUE_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, ITEM_TYPE TEXT NOT NULL,
            ITEM_ID TEXT NOT NULL, TITLE TEXT NOT NULL, DESCRIPTION TEXT, SEARCH_TEXT TEXT NOT NULL,
            FACETS_JSON TEXT NOT NULL, SECURITY_RESOURCE_TYPE TEXT NOT NULL, SECURITY_RESOURCE_ID TEXT,
            FRESHNESS_AT TEXT, STATUS TEXT NOT NULL DEFAULT 'ACTIVE', UPDATED_AT TEXT NOT NULL,
            UNIQUE(ORGANIZATION_ID,ITEM_TYPE,ITEM_ID)
        );
        CREATE TABLE IF NOT EXISTS INTEGRATION_INCIDENTS (
            INCIDENT_ID TEXT PRIMARY KEY, ORGANIZATION_ID TEXT NOT NULL, CONNECTION_ID TEXT,
            SEVERITY TEXT NOT NULL, TITLE TEXT NOT NULL, DESCRIPTION TEXT, STATUS TEXT NOT NULL DEFAULT 'OPEN',
            FIRST_DETECTED_AT TEXT NOT NULL, LAST_DETECTED_AT TEXT NOT NULL, ACKNOWLEDGED_BY TEXT,
            ACKNOWLEDGED_AT TEXT, RESOLVED_BY TEXT, RESOLVED_AT TEXT
        );
        CREATE INDEX IF NOT EXISTS IDX_CONNECTION_ORG ON INTEGRATION_CONNECTIONS(ORGANIZATION_ID,STATUS);
        CREATE INDEX IF NOT EXISTS IDX_RUN_CONNECTION ON INTEGRATION_RUNS(CONNECTION_ID,STARTED_AT DESC);
        CREATE INDEX IF NOT EXISTS IDX_RAW_SOURCE ON RAW_INGESTION_ENVELOPES(CONNECTION_ID,EXTERNAL_TYPE,EXTERNAL_ID);
        CREATE INDEX IF NOT EXISTS IDX_CANONICAL_TYPE ON CANONICAL_OBJECTS(ORGANIZATION_ID,OBJECT_TYPE,UPDATED_AT DESC);
        CREATE INDEX IF NOT EXISTS IDX_THREAD_EDGE_SOURCE ON DIGITAL_THREAD_EDGES(ORGANIZATION_ID,SOURCE_NODE_ID);
        CREATE INDEX IF NOT EXISTS IDX_THREAD_EDGE_TARGET ON DIGITAL_THREAD_EDGES(ORGANIZATION_ID,TARGET_NODE_ID);
        CREATE INDEX IF NOT EXISTS IDX_CATALOGUE_SEARCH ON INFORMATION_CATALOGUE(ORGANIZATION_ID,ITEM_TYPE,STATUS);
        """
    )
    for connector_type, spec in CONNECTOR_TYPES.items():
        conn.execute(
            """INSERT INTO CONNECTOR_TYPES
               (CONNECTOR_TYPE,CATEGORY,VERSION,CAPABILITIES_JSON,CONFIGURATION_SCHEMA_JSON,CREDENTIAL_SCHEMA_JSON,STATUS,CREATED_AT,UPDATED_AT)
               VALUES (?,?,?,?,?,?,'ACTIVE',?,?)
               ON CONFLICT(CONNECTOR_TYPE) DO UPDATE SET VERSION=excluded.VERSION,CAPABILITIES_JSON=excluded.CAPABILITIES_JSON,
                   CONFIGURATION_SCHEMA_JSON=excluded.CONFIGURATION_SCHEMA_JSON,CREDENTIAL_SCHEMA_JSON=excluded.CREDENTIAL_SCHEMA_JSON,UPDATED_AT=excluded.UPDATED_AT""",
            (connector_type, spec["category"], spec["version"], json.dumps(spec["capabilities"]),
             json.dumps(spec["configuration"]), json.dumps(spec["credentials"]), now, now),
        )
