"""Provider-neutral immutable object storage contract."""

from typing import Protocol


class ObjectStore(Protocol):
    def key_for(self, object_hash: str) -> str: ...

    def exists(self, object_hash: str) -> bool: ...

    def put(self, object_hash: str, payload: bytes) -> bool: ...

    def get(self, object_hash: str) -> bytes: ...

    def delete(self, object_hash: str) -> None: ...

    def size(self, object_hash: str) -> int: ...
