"""Frozen Stage 2.4 scoring and target-mapping rules."""

READINESS_WEIGHTS = {
    "STRUCTURAL_CLARITY": .15,
    "FORMULA_RESOLVABILITY": .15,
    "DEPENDENCY_COMPLETENESS": .15,
    "EXTERNAL_RESOLUTION": .10,
    "AUTOMATION_MIGRATABILITY": .10,
    "CONTROL_COMPLETENESS": .10,
    "DATA_MODEL_CLARITY": .10,
    "CHANGE_STABILITY": .05,
    "BLOCKER_ADJUSTMENT": .10,
}

MODE_FACTORS = {
    "AUTO_MIGRATABLE": 1.0,
    "ASSISTED_MIGRATION": .65,
    "MANUAL_REENGINEERING": .25,
    "RETAIN_IN_EXCEL": .15,
    "UNSUPPORTED": 0.0,
    "RETIRE": 1.0,
}

TARGET_RULES = {
    "TABLE": ("DATABASE_TABLE", "Data Platform", "TABLE_TO_RELATIONAL_MODEL"),
    "NAMED_RANGE": ("CONFIGURATION_PARAMETER", "Configuration Service", "NAME_TO_TYPED_CONFIGURATION"),
    "FORMULA_PATTERN": ("CALCULATION_RULE", "Calculation Service", "FORMULA_TO_TESTED_RULE"),
    "SHEET": ("NATIVE_VIEW", "Experience Layer", "SHEET_TO_FORM_OR_GRID"),
    "VBA_PROJECT": ("AUTOMATION_SERVICE", "Automation Platform", "VBA_CAPABILITY_REENGINEERING"),
    "POWER_QUERY": ("ETL_PIPELINE", "Integration Platform", "QUERY_TO_MANAGED_PIPELINE"),
    "CONNECTION": ("MANAGED_CONNECTOR", "Integration Platform", "CONNECTION_TO_SECRETED_CONNECTOR"),
    "EXTERNAL_LINK": ("SERVICE_CONTRACT", "Integration Platform", "WORKBOOK_LINK_TO_API_OR_DATASET"),
    "PIVOT_TABLE": ("ANALYTICS_VIEW", "Reporting Platform", "PIVOT_TO_SEMANTIC_VIEW"),
    "CHART": ("DASHBOARD_COMPONENT", "Reporting Platform", "CHART_TO_DASHBOARD"),
    "VALIDATION": ("INPUT_POLICY", "Policy Service", "VALIDATION_TO_API_AND_UI_CONSTRAINT"),
    "CONTROL": ("GOVERNANCE_CONTROL", "Control Plane", "CONTROL_PRESERVATION"),
    "DOMAIN": ("DOMAIN_SERVICE", "Application Platform", "DEPENDENCY_COMPONENT_TO_SERVICE"),
}

SIMPLE_FUNCTIONS = {"SUM", "SUMIF", "SUMIFS", "COUNT", "COUNTIF", "COUNTIFS", "AVERAGE", "MIN", "MAX", "IF", "ROUND"}
DYNAMIC_FUNCTIONS = {"INDIRECT", "OFFSET", "CELL", "ADDRESS"}
LOOKUP_FUNCTIONS = {"VLOOKUP", "HLOOKUP", "XLOOKUP", "INDEX", "MATCH"}
